# Generated by Django 6.0.3 on 2026-03-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='phonenumber',
            table='phone_numbers',
        ),
    ]
